### ISSUE TITLE
Require development dependency boot issue

### ISSUE THREAD

**Issue by redxeth** [Origen-SDK/origen_app_generators#1]
Attempt to boot a gem from an app is showing issues with development type dependencies.

(to help with confusion, will refer to:  APP <-- GEM <-- SUB-GEMS)

Dev dependencies of a GEM (other gems a GEM requires but only in dev mode, referred to as SUB-GEMS above) are handled by adding needed SUB-GEMS to the GEM Gemfile (old way used to be to add_development_dependency in GEM gemspec but that method has been deprecated).

Unfortunately the toplevel model of the GEM has a statement:

`Dir.glob("#File.dirname(__FILE__)}/**/**.rb")`

that requiring development test code which may have a SUB-GEM that is not required already when booting from the APP.   Solution is to move the development test code (dut.rb and dut_controller.rb) out to another directory.

Needed changes would then be to modify GEM toplevel model to only require `lib/GEMname/**/*.rb` for production mode-- and to modify GEM boot.rb to also recursively require `lib/GEMname_dev/**/*.rb`.

Please update origen_app_generators so that new gems follow this new convention to mitigate ussues.

**Comment by ginty** [comment]
Fixed in 0.3.2
